version: '3.9'

services:
  plants:
    build:
      context: .
    container_name: plants
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - measurements
    volumes:
      - ./app:/app/app
    tty: true

  sql:
    build:
      context: ./app/service/sql
      dockerfile: Dockerfile
    container_name: sql
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./app/service/sql/init_database_plants.sh:/docker-entrypoint-initdb.d/init_database_plants.sh
      - ./app/service/sql/init_table_plants.sh:/docker-entrypoint-initdb.d/init_table_plants.sh
      - ./app/service/sql/init_table_plant_types.sh:/docker-entrypoint-initdb.d/init_table_plant_types.sh
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "localhost",
          "-p",
          "${POSTGRES_PORT}",
          "-q",
          "-U",
          "${POSTGRES_USER}"
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s