version: '3.9'

services:
  measurements:
    build:
      context: ../measurements
    container_name: measurements
    env_file:
      - ../measurements/.env
    depends_on:
      sql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ../measurements/app:/app
    tty: true

  plants:
    build:
      context: .
    container_name: plants
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - measurements
    volumes:
      - ./app:/app/app
    tty: true

  sql:
    build:
      context: ./app/service/sql
      dockerfile: Dockerfile
    container_name: sql
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./app/service/sql/init_database_plants.sh:/docker-entrypoint-initdb.d/init_database_plants.sh
      - ./app/service/sql/init_table_plants.sh:/docker-entrypoint-initdb.d/init_table_plants.sh
      - ../measurements/app/service/sql/init_database_measurements.sh:/docker-entrypoint-initdb.d/init_database_measurements.sh
      - ../measurements/app/service/sql/init_table_device_plant.sh:/docker-entrypoint-initdb.d/init_table_device_plant.sh
      - ../measurements/app/service/sql/init_table_measurements.sh:/docker-entrypoint-initdb.d/init_table_measurements.sh
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "localhost",
          "-p",
          "${POSTGRES_PORT}",
          "-q",
          "-U",
          "${POSTGRES_USER}"
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s

  rabbitmq:
    build:
      context: ../measurements/app/service/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test:
        [
          "CMD",
          "rabbitmq-diagnostics",
          "check_port_connectivity"
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s

  # simulator:
  #   build:
  #     context: ../simulator
  #   container_name: simulator
  #   env_file:
  #     - ../simulator/.env
  #   depends_on:
  #     - plants
  #     - measurements
  #   volumes:
  #     - ../simulator/src:/app/src