version: '3.9'

services:

  plants:
    build:
      context: .
    container_name: plants
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      sql:
        condition: service_healthy
    volumes:
      - ./app:/app/app
    tty: true

  sql:
    build:
      context: ./app/service/sql
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./app/service/sql:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "localhost",
          "-p",
          "5432",
          "-q",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s